# Generated by Django 3.2.5 on 2021-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('GroupProfile', '0001_initial'),
        ('vocabularies', '0002_auto_20210714_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'permissions': (('ownwer', 'Owner'), ('participant', 'Participant'), ('spectator', 'Spectator'))},
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='groups',
            field=models.ManyToManyField(to='GroupProfile.GroupProfile'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='profiles',
            field=models.ManyToManyField(to='Profile.Profile'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='term_count',
            field=models.IntegerField(default=0),
        ),
    ]
