# Generated by Django 3.2.5 on 2021-07-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0002_auto_20210714_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='term_count',
            field=models.IntegerField(default=0),
        ),
    ]
