# Generated by Django 3.2.5 on 2021-07-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupProfile', '0001_initial'),
        ('Profile', '0001_initial'),
        ('vocabularies', '0003_auto_20210717_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='description',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='groups',
            field=models.ManyToManyField(blank=True, to='GroupProfile.GroupProfile'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='Profile.Profile'),
        ),
    ]
