# Generated by Django 3.2.5 on 2021-07-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0004_auto_20210717_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'permissions': [('owner', 'Owner'), ('participant', 'Participant'), ('spectator', 'Spectator')]},
        ),
    ]
