# Generated by Django 3.2.5 on 2021-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0005_alter_vocabulary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='state',
            field=models.IntegerField(choices=[(1, 'Dev'), (2, 'Review'), (3, 'Live')], default=1),
        ),
    ]
