# Generated by Django 3.2.5 on 2021-07-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0006_vocabulary_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='state',
            field=models.CharField(choices=[('Development', 'Dev'), ('Review', 'Review'), ('Live', 'Live')], default='Development', max_length=30),
        ),
    ]
