# Generated by Django 3.2.5 on 2021-07-28 13:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0007_alter_vocabulary_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='prefixes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
        ),
    ]
