# Generated by Django 3.2.5 on 2021-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0007_alter_vocabulary_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='description',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='urispace',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
