# Generated by Django 3.2.5 on 2021-07-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0003_alter_vocabulary_term_count'),
        ('vocabularies', '0008_auto_20210728_1239'),
    ]

    operations = [
    ]
