# Generated by Django 3.2.5 on 2021-07-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0008_auto_20210728_1239'),
        ('vocabularies', '0008_vocabulary_prefixes'),
    ]

    operations = [
    ]
