# Generated by Django 3.2.5 on 2021-07-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0008_vocabulary_prefixes'),
        ('vocabularies', '0009_merge_20210728_1342'),
    ]

    operations = [
    ]
