# Generated by Django 3.2.5 on 2021-07-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0010_merge_20210728_1555'),
        ('vocabularies', '0011_merge_20210728_1552'),
    ]

    operations = [
    ]
