# Generated by Django 3.2.5 on 2021-08-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0012_merge_20210728_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
