stages:
  - test

variables:
  DOCKER_HOST: tcp://dockerdind:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    alias: dockerdind

image: docker:latest

test-all:
  tags:
    - compose
  stage: test
  script:
    - docker compose -f docker-compose.test.yml build
    - docker compose -f docker-compose.test.yml up --abort-on-container-exit
  after_script:
    - docker compose rm -f
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
