# Generated by Django 3.2.5 on 2021-07-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabularies', '0005_alter_vocabulary_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('vocabulary', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vocabularies.vocabulary')),
            ],
        ),
    ]
