# Generated by Django 3.2.5 on 2021-07-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0005_alter_vocabulary_options'),
        ('Term', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabularies.vocabulary'),
        ),
    ]
