# Generated by Django 3.2.5 on 2021-07-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Term', '0002_alter_term_vocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
