# Generated by Django 3.2.5 on 2021-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_notification_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
