# Generated by Django 3.2.5 on 2021-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('WARNING', 'Warning')], max_length=30, null=True),
        ),
    ]
