# Generated by Django 3.2.5 on 2021-08-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0004_notification_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('WARNING', 'Warning')], default='DEFAULT VALUE', max_length=30),
        ),
    ]
