# Generated by Django 3.2.5 on 2021-08-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0005_auto_20210812_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='state',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('WARNING', 'Warning')], default='ERROR', max_length=30),
        ),
    ]
