# Generated by Django 3.2.5 on 2021-08-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GroupProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='group_owner',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='group_owner_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
