# Generated by Django 3.2.5 on 2021-08-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupProfile', '0002_auto_20210801_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='group_owner_1',
            new_name='group_owner',
        ),
    ]
