# Generated by Django 3.2.5 on 2021-08-01 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GroupProfile', '0003_rename_group_owner_1_groupprofile_group_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='group_owner',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='group_owner1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
