# Generated by Django 3.2.5 on 2021-08-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupProfile', '0004_auto_20210801_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='group_owner1',
            new_name='group_owner',
        ),
    ]
