# Generated by Django 3.2.5 on 2021-07-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0009_merge_20210728_1342'),
        ('Term', '0002_alter_term_vocabulary'),
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Term.term'),
        ),
        migrations.AddField(
            model_name='tag',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabularies.vocabulary'),
        ),
    ]
