# Generated by Django 3.2.5 on 2021-07-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post_date',
            field=models.CharField(default='', max_length=126),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('purple', 'Purple')], default='green', max_length=30),
        ),
    ]
