# Generated by Django 3.2.5 on 2021-07-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0007_auto_20210728_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('purple', 'Purple')], default='red', max_length=30),
        ),
    ]
