# Generated by Django 3.2.7 on 2021-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0028_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('purple', 'Purple')], default='blue', max_length=30),
        ),
    ]
