name: tests

on:
  push:
    # branches: [ dependency-updates ]
  #   branches: [ master, main, development]
    branches-ignore:
      - master
      - main
      - development
  pull_request:
    branches: [ master, main, development]
  workflow_dispatch:

jobs:
  test-all:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run tests
        shell: bash
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml build
          docker compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from web

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Remove Docker containers
        if: always()
        shell: bash
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml down
